# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Database.Repo.insert!(%Database.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Database.Repo
alias Database.Catalog.Question
alias Database.Catalog.Answer
alias Database.Catalog.Pack

questions = [
["178", "The rank of Estonia in world population density."],
["148", "The number of episodes of the TV series The Fresh Prince of Bel-Air on NBC from 1990 to 1996."],
["850", "The maximum possible Fair Isaac credit score."],
["74", "The number of stars obtained by SpongeBob SquarePants in his driving school."],
["103", "The atomic number of lawrencium, an actinide."],
["153", "The code for \"mental processes & intelligence\" in the Dewey Decimal Classification."],
["147", "The final score of the losing team in the NBA game in which Wilt Chamberlain scored 100 points."],
["5300", "The number of gum wrappers that Steve Fletcher has, the record for the largest gum wrapper collection."],
["10000000000", "The number of times the original Pac Man has been played as estimated by Namco, the manufacturers of Pac Man."],
["46", "The number of samurai, out of 47, who carried out the attack in the historical Ako vendetta."],
["8674", "The number of unique words in the Hebrew Bible."],
["88", "The number of keys on a piano (36 black and 52 white)."],
["400", "The number of years in a period of the Gregorian calendar, of which 97 are leap years and 303 are common."],
["213", "The code for character \"Õ\" in codepages such as ISO-8859-1 and UTF-8."],
["998402801", "The number of entries of distinct astronomical objects in The Guide Star Catalog II."],
["250", "The number of Pokémon originally available in Pokémon Gold and Silver before Celebi was added."],
["84", "The code for international direct dial phone calls to Vietnam."],
["135", "The angle between two planets in degrees so that they are in an astrological aspect called a sesquiquadrate."],
["69", "The atomic number of thulium, a lanthanide."],
["185", "The record number of singles hit by St. Louis Cardinals Jesse Burkett in 1899."],
["451", "The temperature at which the paper in books ignites, giving the name to Ray Bradbury's novel Fahrenheit 451."],
["131", "The medical emergency telephone number in Chile."],
["1096000000", "The population of India in 2007."],
["100000000000", "The number of neurons in the human brain."],
["171", "The record number of goals scored by France at the 1998 World Cup."],
["400000", "The number of morphine addicts the Civil War produced."],
["245", "The number of Jewish singers who returned from captivity in Babylon in circa 538 BCE BC following the rise of Cyrus the Great and the Persian Empire."],
["313", "The number of Muslims who fought in the Battle of Badr against Muhammad's, and by extension, Islam's, foes."],
["110", "A common name for mains electricity in North America, despite the nominal voltage actually being 120V (range 110-120)."],
["525998433", "The number of distinct websites as of November 2011."],
["714", "The number of home runs Babe Ruth scored in his career."],
["614", "The number of Commandments, according to Rabbi Fackenheimin, that should be in Judaism, vs. the traditional 613."],
["22834", "The feet above sea level of the highest mountain in the Western Hemisphere, Mount Aconcagua in Argentina."],
["67890", "The number of largest decimal places of π that have been recited from memory."],
["43", "The maximum number of cars participating in a NASCAR race in the Cup Series or Nationwide Series."],
["3", "The number of consecutive successful attempts in a hat trick in sports."],
["470", "The minimum length in yards from the tee to the hole on a Par 5."],
["174", "The rank of Barbados in world population."],
["77", "The atomic number of iridium."],
["118", "The number of decibels of the loudest burp, held by record-holder Paul Hunn, which is as loud as a chainsaw."],
["5200", "The number of standard size of a legion in the Roman Empire."],
["67", "The highest two-digit odd number not presently designating any highway in the Interstate Highway System of the United States."],
["17000", "The length in km of bicycle lanes with special bicycle traffic lights in the Netherlands."],
["361", "The number of positions on a standard 19 x 19 Go board."],
["1000", "The number of elephants it took to bring in the material to build the Taj Mahal from various parts of India."],
["248", "The number of organs in the human body as traditionally depicted."],
["33", "The temperature at which water boils according to the Newton scale."],
["525", "The number of scan lines in the NTSC television standard."],
["28", "The number of Chinese constellations, \"Xiu\" or \"mansions\" (a literal translation), equivalent to the 12 western zodiac constellations."],
["137", "The California Penal Code for \"Offer bribe to influence testimony\"."],
["6909", "The number of estimate for the linguistic diversity of living human languages or dialects."],
["1337", "The number that spells \"leet\" in leetspeak."],
["13", "The speed of rush hour traffic on average in kilometres per hour in London."],
["125", "Years in a quasquicentennial."],
["1729", "The smallest number representable in two different ways as a sum of two positive cubes, as Ramanujan stated on the spot."],
["110", "The number of stories (by common reckoning) of the Sears Tower in Chicago."],
["162", "Total number of baseball games each team plays during a regular season in Major League Baseball."],
["217", "The room in Stephen King's novel \"The Shining\", that plays a central part in the story as it is haunted."],
["693", "The number of sections in Ludwig Wittgenstein's Philosophical Investigations."],
["24", "The number of a car in the NASCAR Sprint Cup Series owned by Hendrick Motorsports."],
["77", "The atomic number of iridium."],
["229", "The lowest individual batting score not achieved by any player in test match cricket."],
["123", "The telephone number of the speaking clock for the correct time in the United Kingdom."],
["205726", "The number of gambling slots in Nevada in 1999, which was one slot for every 10 people residing there."],
["180", "The number of litres of saliva in one day that cattle can produce."],
["46", "The number of slices of pizza an average American kid eats in a year."],
["59", "The number corresponding to the last second in a given minute."],
["137", "The atomic number of an element not yet observed called Untriseptium."],
["950000", "The pounds of bacon that Burger King restaurants prepare each year for their breakfast customers."],
["99", "A common price ending in psychological pricing."],
["24", "The number of points on a backgammon board."],
["143", "The number of episodes of the TV series The Adventures of Robin Hood on CBS from 1955 to 1959."],
["73", "The single-season home run record in baseball set by Barry Bonds in 2001."],
["202", "The HTTP status code indicating the request was accepted but has not yet been fulfilled."],
["175", "The number of weeks that professional golfer David Toms spent in the top-10 of the Official World Golf Rankings between 2001 and 2006."],
["42", "The number of US gallons in a barrel of oil."],
["50", "The approximate number of times a mother hen turns her egg in a day so the yolk does not stick to the shell."],
["187", "187th Street in the Washington Heights section of Manhattan."],
["360", "The number of degrees in a circle for the purpose of angular measurement."],
["142", "The number of home-based business ideas included in the 142 Now packet."],
["100000000000", "The number of neurons in the human brain."],
["159", "The number of isomers of C11H24."],
["64374", "The number of km in length the greatest mountain range extends from (Arctic Ocean to the Atlantic Ocean)."],
["125000", "The number of average strands of hair in the human head."],
["2380", "Kg of plasticine used for the movie \"Chicken Run\", the most plasticine used in an animated movie."],
["440", "The standard frequency in hertz to which most orchestras tune the pitch A above middle C."],
["114", "The police non-emergency number in Denmark."],
["243", "The number of isotopes or variations of elements calculated by Dr. Plichta."],
["614", "The number of Commandments, according to Rabbi Fackenheimin, that should be in Judaism, vs. the traditional 613."],
["46", "The number of mountains in the 46 peaks of the Adirondack mountain range."],
["80", "A common limit for the characters per line in computing (derived from the number of columns in IBM cards)."],
["58", "The number of counties in California."],
["256", "The number of NFL regular season football games."],
["587", "The outgoing port for email message submission."],
["649", "The number of Pokémon as of Pokémon Black and White versions."],
["147", "The highest possible break in snooker, in the absense of fouls and refereeing errors."],
["998402801", "The number of entries of distinct astronomical objects in The Guide Star Catalog II."],
["911", "The number of days after September 11th that the Madrid Attack took place."],
["225", "The longest distance in miles a deepwater lobster has been recorded to travel."],
["129", "The combined 2-year total of home runs for baseball's Sammy Sosa with 66 home runs in 1999 and 63 in 2000."],
["107", "A common police code denoting a suspicious person."],
["52", "The number of cards in a standard deck of playing cards, not counting Jokers or advertisement cards."],
["64374", "The number of km in length the greatest mountain range extends from (Arctic Ocean to the Atlantic Ocean)."],
["83", "The atomic number of bismuth."],
["202", "The area code assigned to Washington D.C."],
["15", "The number of days in each of the 24 cycles of the Chinese calendar."],
["285", "The total number of Rules of Acquisition in Star Trek."],
["40", "The customary number of hours in a regular workweek in some Western countries."],
["42", "The answer to the Ultimate Question of Life, the Universe, and Everything."],
["75", "The age in years that the Saguaro Cactus, found in southwestern US, must be to grow branches."],
["6", "The number of points on a Star of David."],
["103", "The atomic number of lawrencium, an actinide."],
["79", "The record for cumulative weeks at #1 on the Billboard charts, held by Elvis Presley."],
["135", "The atomic number of an element temporarily called untriquadium."],
["2701", "A plot triviality in Neal Stephenson's \"Cryptonomicon\"."],
["106", "The maximum number of characters filenames can have in Joliet, an extension to the ISO 9660 file system."],
["44", "The number of candles in a box of Hanukkah candles."],
["39", "The duration, in nanoseconds, of the nuclear reaction in the largest nuclear explosion ever performed (Tsar bomb)."],
["54", "The number of countries in Africa."],
["67890", "The number of largest decimal places of π that have been recited from memory."],
["336", "The number of dimples on an American golf ball."],
["490", "The number of times Jesus told Peter to forgive his brother in the Gospel of Matthew."],
["5", "The number of points in a pentagram."],
["121", "The atomic number of the undiscovered chemical element Unbiunium."],
["190", "The number of member states of the United Nations."],
["3000000000", "The number of base pairs in the human genome."],
["28", "The number of days the curing time of concrete is classically considered to be."],
["67890", "The number of largest decimal places of π that have been recited from memory."],
["121", "The number for voicemail for mobile phones on the Vodafone network."],
["43", "The maximum number of cars participating in a NASCAR race in the Cup Series or Nationwide Series."],
["169", "The height in feet that Buddha Dordenma, a Shakyamuni Buddha statue under construction in the mountains of Bhutan, once completed, would be."],
["1362310155", "The total number of items of mail that went through the Canadian postal system in 1950."],
["58000000", "The number of customers McDonald restaurants serve food and drink to on a daily basis in 2011."],
["73", "The favorite number of The Big Bang Theory's character Sheldon Cooper."],
["6000000000000000000", "The number of transistor produced worldwide in 2008."],
["56000000000", "The number of web pages indexed by Google as of 2010."],
["88", "The number of constellations in the sky as defined by the International Astronomical Union."],
["400000000000", "The number of stars in the Milky Way galaxy."],
["64", "Number of codons in the RNA codon table under genetic code."],
["2380", "Kg of plasticine used for the movie \"Chicken Run\", the most plasticine used in an animated movie."],
["15250", "The number of times the average driver will honk in a lifetime."],
["111", "The number occasionally referred to as \"eleventy-one\", as read in The Fellowship of the Ring by J.R.R."],
["218", "Votes required in the US House of Representatives to achieve a majority as of 2008."],
["2701", "A plot triviality in Neal Stephenson's \"Cryptonomicon\"."],
["235", "The atomic mass number of an important isotope of the element uranium, the fissile isotope which is used as the fuel for nuclear reactors and in some nuclear weapons."],
["149000000", "The number of kilometres from the Earth the sun is."],
["123", "The emergency telephone number in Colombia."],
["5", "The number of kyu (pupil) grades in judo."],
["123", "The medical emergency telephone number in Egypt."],
["1362310155", "The total number of items of mail that went through the Canadian postal system in 1950."],
["44000000", "The cost in dollars to make the movie \"Cleopatra\" in 1963."],
["46", "The number of human chromosomes."],
["564000", "The number of words in War and Peace by Leo Tolstoy."],
["84", "The code for international direct dial phone calls to Vietnam."],
["600", "The advertised number of miles that NASCAR runs in the Coca-Cola 600, the longest race on any of the NASCAR circuits."],
["195", "The distance off the coast of Malta that the ocean liner RMS Franconia was sunk by German torpedoes in 1916."],
["168", "Hours in a week."],
["26", "The number of miles in a marathon rounded down (26 miles and 385 yards)."],
["27", "The number of bones in the human foot."],
["34", "The lucky number of Victor Pelevin's protagonist Stepan Mikhailov in the novel Numbers."],
["43687", "The number of toilet related accidents in the United States in 1996."],
["34", "The lucky number of Victor Pelevin's protagonist Stepan Mikhailov in the novel Numbers."],
["181", "The wing area of a Boeing 757 airplane in meters."],
["16", "The number of personality types in the Myers-Briggs classification system."],
["198", "The number of places listed on the United States National Register of Historic Places in Los Angeles."],
["119", "The default port for unencrypted NNTP connections."],
["164", "The number of episodes that the TV show Mad About You ran on NBC from 1992 to 1999."],
["111", "The number occasionally referred to as \"eleventy-one\", as read in The Fellowship of the Ring by J.R.R."],
["511", "The number of collaborators mathematician Paul Erdős had."],
["83", "The highest UHF channel on older televisions made before the late 1970s."],
["500000", "The number of tons of dog excrement dumped annually on the streets of Paris."],
["56", "The number of layers of the Universe according to Aristotle (Earth plus 55 crystalline spheres above it)."],
["58", "The number of usable cells on a Hexxagon game board."],
["217", "The area code for central Illinois."],
["204", "The HTTP status code indicating the request was received but there is no response to the request."],
["273", "The zero of the Celsius temperature scale (to the nearest whole number) in Kelvin."],
["49", "The number of days and night Siddhartha Gautama spent meditating as a holy man."],
["304", "The record number of wickets taken in English cricket season by Tich Freeman in 1928."],
["270", "The average number of days in human pregnancy."],
["33", "The number of workers trapped, and also the number of survivors of the 2010 Copiapó mining accident."],
["5000", "The number of base pairs in the DNA of the simplest viruses."],
["400000000000", "The number of stars in the Milky Way galaxy."],
["89", "The atomic number of actinium."],
["396", "The displacement in cubic inches of early Chevrolet Big-Block engines."],
["129", "The number of episodes of the TV series Becker that ran on CBS from 1998 to 2004."],
["60", "A common speed limit (mph) for freeways in many US states."],
["85", "The IQ and nickname of Aaron in Alien 3."],
["231", "The number of cubic inches in a U.S. liquid gallon."],
["177", "The rank of Netherlands Antilles in world population."],
["100000000000", "The number of neurons in the human brain."],
["157", "The elevation in meters of Atalanti Island in the North Euboean Gulf of the Aegean Sea."],
["256", "The number of NFL regular season football games."],
["205726", "The number of gambling slots in Nevada in 1999, which was one slot for every 10 people residing there."],
["59", "The number on a button commonly worn by feminist activists in the 1970s (based on the claim that a woman earned 59 cents to an equally qualified man's dollar)."],
["613", "A significant number in Judaism, as its metaphysics, the Kabbalah, views every full entity as divisible into 613 parts."],
["490", "The number of Pokémon available as of the release of Pokémon Diamond and Pearl (excluding event Pokémon)."],
["334", "The long-time highest score in Test cricket (held by Sir Donald Bradman and Mark Taylor)."],
["102", "The atomic number of nobelium, an actinide."],
["10", "The number of hydrogen atoms in butane, a hydrocarbon."],
["16777216", "The number of different colors that can be generated using the hex code system in HTML."],
["2380", "kg of plasticine used for the movie \"Chicken Run\", the most plasticine used in an animated movie."],
["160", "The number of characters permitted in a standard short message service in Australia and Europe."],
["1337", "The number that spells \"leet\" in leetspeak."],
["250000", "The number of drivers that fall asleep while driving each day in the US, according to Harvard Medical School."],
["930000", "The number of words in the King James Version of the Bible."],
["361", "The number of positions on a standard 19 x 19 Go board."],
["204", "The HTTP status code indicating the request was received but there is no response to the request."],
["101", "The temperature in Fahrenheit of milk when it leaves the body of a cow."],
["235", "The number of three interstate highways in the United States, located in the states of Iowa, Kansas, and Oklahoma."],
["231", "The number of cubic inches in a U.S. liquid gallon."],
["360000", "The number of words definitions in the New Oxford Dictionary of English."],
["207", "The area code for the US state of Maine."],
["179", "The number of even numbered days of the year."],
["142600", "tonnes of gold mined in the world by the end of 2000."],
["27", "The number of countries in the European Union (as of August 2011)."],
["98", "The highest jersey number allowed in the National Hockey League (as 99 was retired by the entire league to honor Wayne Gretzky)."],
["189", "The rank of Brazil in population density."],
["48", "The number of Ptolemaic constellations."],
["8674", "The number of unique words in the Hebrew Bible."],
["100000000000000000000", "The of rate of hyperinflation in Zimbabwe by February 2009."],
["36", "The number of vehicles that run in each race of NASCAR's Camping World Truck Series."],
["203", "The HTTP status code indicating partial information."],
["511", "The number of collaborators mathematician Paul Erdős had."],
["35", "The percentage of all bingo players are under the age of 35."],
["173", "years it takes for all the water in Lake Superior to be changed."],
["6000000000000000000", "The number of transistor produced worldwide in 2008."],
["383", "The cubic displacement in inches of a 350cid Small Block Chevrolet with a 400cid SBC crankshaft."],
["222", "The number for Historical Books of the Old Testament in the Dewey Decimal System."],
["99", "The highest jersey number allowed in most major league sports."],
["119", "A number to report children / youth at risk in France."],
["500", "The longest advertised distance of the IndyCar Series and its premier race, the Indianapolis 500."],
["107", "The atomic number of bohrium."],
["32", "The size, in bits, of certain integer data types, used in computer representations of numbers."],
["16777216", "The number of different colors that can be generated using the hex code system in HTML."],
["115", "The atomic number of an element temporarily called ununpentium."],
["43", "The maximum number of cars participating in a NASCAR race in the Cup Series or Nationwide Series."],
["5200", "The number of standard size of a legion in the Roman Empire."],
["240", "The cholesterol level above which is considered high risk."],
["100000000000", "The number of neurons in the human brain."],
["5500000000000000", "The number of estimated ants on Earth alive at any one time."],
["60000000000000000000", "The permutations of a 10-character password on a 95-character set found on standard computer keyboards."],
["525998433", "The number of distinct websites as of November 2011."],
["1337", "The weight in pounds of the biggest pumpkin in the world."],
["525998433", "The number of distinct websites as of November 2011."],
["276", "The highest number of rounds in boxing history, in a bare-knuckle fight in 1825 that saw Jack Jones beat Patsy Tunney after 4hr 30min."],
["209", "The basketball record for most three pointers in a row."],
["102", "The atomic number of nobelium, an actinide."],
["6000000000000000000", "The number of transistor produced worldwide in 2008."],
["613", "A significant number in Judaism, as its metaphysics, the Kabbalah, views every full entity as divisible into 613 parts."],
["36", "The perfect score on the ACT."],
["3585", "The depth in metres of the deepest mine in the world, the East Rand mine."],
["280000000000000", "The number of possible unique physical addresses."],
["205726", "The number of gambling slots in Nevada in 1999, which was one slot for every 10 people residing there."],
["217", "The room in Stephen King's novel \"The Shining\", that plays a central part in the story as it is haunted."],
["729", "The number of times a philosopher's pleasure is greater than a tyrant's pleasure according to Plato in the Republic."],
["76", "The atomic number of osmium."],
["25", "The (critical) number of Florida electoral votes for the 2000 U.S. presidential election."],
["201", "The title of an episode of South Park."],
["198", "The rank of Hey Joe (1966) by Jimi Hendrix on Rolling Stone magazine's list of The 500 Greatest Songs of All Time."],
["170", "170 is the maximum check-out possible in a standard game of darts (where the final score must be a double)."],
["107", "The number of Nobel Prize in Literature laureates."],
["950000", "The pounds of bacon that Burger King restaurants prepare each year for their breakfast customers."],
["49", "The number of days and night Siddhartha Gautama spent meditating as a holy man."],
["7", "The number of days in a week."],
["1500", "The approximate number of peanut butter sandwiches the average American kid will eat by high school graduation."],
["161", "The number of different ways to bet on a roulette wheel."],
["1000000000000", "The number of bacteria on the surface of the human body."],
["22000", "The approximate number of workers who died during the building of the Panama Canal due to accidents and diseases."],
["32", "The size, in bits, of certain integer data types, used in computer representations of numbers."],
["202", "The area code assigned to Washington D.C."],
["49", "The number of days and night Siddhartha Gautama spent meditating as a holy man."],
["82", "The atomic number of lead."],
["1982", "The average price for a major league baseball game ticket in 2004 in cents."],
["197", "The rank of the Solomon Islands in population density."],
["58", "The minimum wind speed (mph) needed to issue a Severe Thunderstorm Warning."],
["364", "The total number of gifts received in the song \"The Twelve Days of Christmas\"."],
["81", "The number of squares on a shogi playing board."],
["188000", "The number of lakes in Finland, which is also known as \"The land of of the thousand lakes\"."],
["243", "The number of Earth Days for the planet Venus to complete one Venetian day, one revolution."],
["1096000000", "The population of India in 2007."],
["205726", "The number of gambling slots in Nevada in 1999, which was one slot for every 10 people residing there."],
["198", "The rank of Hey Joe (1966) by Jimi Hendrix on Rolling Stone magazine's list of The 500 Greatest Songs of All Time."],
["1631", "two London bible printers accidentally left \"not\" out of the 7th commandment, which then read \"Thou shalt commit adultery.\"."],
["126", "The seventh magic number in nuclear physics (2, 8, 20, 28, 50, 82, 126)."],
["149000000", "The number of kilometres from the Earth the sun is."],
["564000", "The number of words in War and Peace by Leo Tolstoy."],
["564000", "The number of words in War and Peace by Leo Tolstoy."],
["273", "The number of seconds in American composer John Cage's piano composition 4'33\" of silence, in three movements."],
["755", "The number of home runs Hank Aaron ended his career with in 1976, a Major League record at the time."],
["181", "The atomic number of an element temporarily called Unoctunium."],
["214", "The Dewey Decimal Classification for Theodicy (the problem of evil)."],
["183", "The id number of Issam Hamid Al Bin Ali Al Jayfi, a detainee at Guantanamo Bay."],
["43687", "The number of toilet related accidents in the United States in 1996."],
["215", "The Dewey Decimal Classification for Science and religion."],
["464", "The number of legal positions of the kings in chess, not counting mirrored positions."],
["204", "The HTTP status code indicating the request was received but there is no response to the request."],
["1400000", "The number of species that have been named by the World Resources Institute."],
["27", "The number of grains in some Buddhist rosary (108 divided by 4)."],
["235", "The number of three interstate highways in the United States, located in the states of Iowa, Kansas, and Oklahoma."],
["6000000000000000000", "The number of transistor produced worldwide in 2008."],
["20", "The number of ounces in Venti size coffees at Starbucks coffee shops."],
["69", "The atomic number of thulium, a lanthanide."],
["115", "The atomic number of an element temporarily called ununpentium."],
["40000000", "The number of times lightning hits the ground 40 million times a year in the United States."],
["183", "The number of runs scored by former cricket player Sourav Ganguly in the 1999 Cricket World Cup, second highest in World Cup history, and highest by an Indian in the tournament."],
["2600", "The length of brink in feet of the Canadian \"Horseshoe\" Falls located in Niagara Falls, Ontario."],
["131", "The number serving a monkiker for Indie music."],
["169", "The number of miles that Thomas Sopwith, an English aviation pioneer flew in 3 hours, 40 minutes on December 18, 1910."],
["77", "The atomic number of iridium."],
["313", "The number of Muslims who fought in the Battle of Badr against Muhammad's, and by extension, Islam's, foes."],
["139", "The rank of Oman in world population."],
["900000000", "The approximate number of trees cut down in a year to make the raw materials for US pulp mills and paper."],
["2701", "A plot triviality in Neal Stephenson's \"Cryptonomicon\"."],
["107", "The number of Nobel Prize in Literature laureates."],
["72", "The total number of books in the Holy Bible in the Catholic version."],
["134", "The number of episodes in the TV series Hawaiian Eye that ran on ABC from 1959 to 1963."],
["211", "The SMTP status code system status."],
["146", "The Guinness World Record for the most languages a poem was recited in."],
["267000", "The number of words in James Joyce's Ulysses."],
["37", "The cost in cents of the Whopper Sandwich when Burger King first introduced it in 1957."],
["16777216", "The number of different colors that can be generated using the hex code system in HTML."],
["1600000", "The number of people employed by the Indian railway system in India."],
["225", "The longest distance in miles a deepwater lobster has been recorded to travel."],
["99", "A common price ending in psychological pricing."],
["216", "The ISO's standard for paper sizes."],
["62", "The atomic number of samarium."],
["6000000000000000000", "The number of transistor produced worldwide in 2008."],
["7", "The number of types of viruses according to the Baltimore classification."],
["147", "The highest possible break in snooker, in the absense of fouls and refereeing errors."],
["19", "The final year a person is a teenager."],
["72", "The speed in miles per hour that cheetahs, the fastest land animal, can reach."],
["755", "The number of home runs Hank Aaron ended his career with in 1976, a Major League record at the time."],
["79", "The record for cumulative weeks at #1 on the Billboard charts, held by Elvis Presley."],
["390", "The speed in feet per second that nerve impulses for muscle position travel at."],
["555", "The number of seats of the airliner A380-800."],
["171", "The record number of goals scored by France at the 1998 World Cup."],
["81", "The number of prayers said in the Rosary in each night."],
["8", "The number of furlongs in a mile."],
["44000000", "The cost in dollars to make the movie \"Cleopatra\" in 1963."],
["5300", "The number of gum wrappers that Steve Fletcher has, the record for the largest gum wrapper collection."],
["1311000000", "The population of the People's Republic of China in 2007."],
["55", "The percentage of movies released that are Rated R."],
["43687", "The number of toilet related accidents in the United States in 1996."],
["390", "The speed in feet per second that nerve impulses for muscle position travel at."],
["2055001", "The number of people employed by Wal-mart in 2007."],
["107", "The atomic number of bohrium."],
["139", "The number of episodes of the TV series 3rd Rock from the Sun that ran on NBC from 1996 to 2001."],
["106000000000", "The number of homo sapiens that have lived since speciation."],
["116", "The number of years that the Hundred Years' War between France and England, from 1337 to 1453, actually lasted."],
["2600", "The length of brink in feet of the Canadian \"Horseshoe\" Falls located in Niagara Falls, Ontario."],
["6800", "The approximate number of languages in the world."],
["155", "The number of episodes the TV series Sea Hunt ran in syndication from 1958 to 1961."],
["227", "The number of days Pi Patel was at sea in the popular novel, Life of Pi."],
["10000", "The gallons of saliva an average human produces in a lifetime."],
["107", "A common police code denoting a suspicious person."],
["45000000", "The number of turkeys Americans eat at Thanksgiving annually."],
["328", "The weight in pounds of an ovarian cyst removed from a woman in Galveston, Texas, in 1905, a world record."],
["1750000", "The number of entries in the freedb database of CD track listings as of June 2005."],
["1337", "The number that spells \"leet\" in leetspeak."],
["614", "The number of Commandments, according to Rabbi Fackenheimin, that should be in Judaism, vs. the traditional 613."],
["248", "The number of organs in the human body as traditionally depicted."],
["5880000", "The number of geographic features named by the NIMA GEOnet Names Server."],
["157", "The elevation in meters of Atalanti Island in the North Euboean Gulf of the Aegean Sea."],
["261", "number of possible unfolded tesseract patterns."],
["63", "The number of groats in a guinea in British pre-decimal currency."],
["402000000", "The number of native speakers of English."],
["17", "The maximum number of strokes of a Chinese radical."],
["74", "The number of stars obtained by SpongeBob SquarePants in his driving school."],
["88", "The pounds of oxygen that the adult human body requires daily."],
["366", "The number of days in a leap year."],
["91", "The amount of money one has if one has one coin of each U.S. denomination less than a dollar (penny, nickel, dime, quarter, half dollar) in cents."],
["76", "The atomic number of osmium."],
["157", "The elevation in meters of Atalanti Island in the North Euboean Gulf of the Aegean Sea."],
["40000000", "The number of Americans that have \"chronic halitosis,\" which is bad breath that never goes away."],
["464", "The number of legal positions of the kings in chess, not counting mirrored positions."],
["231", "The number of cubic inches in a U.S. liquid gallon."],
["1337", "The weight in pounds of the biggest pumpkin in the world."],
["85", "The IQ and nickname of Aaron in Alien 3."],
["123", "The telephone number of the speaking clock for the correct time in the United Kingdom."],
["2", "The first magic number in physics."],
["613", "A significant number in Judaism, as its metaphysics, the Kabbalah, views every full entity as divisible into 613 parts."],
["53", "The number of bytes in an Asynchronous Transfer Mode packet."],
["136", "The hottest temperature ever recorded in Fahrenheits at Aziziya, Libya in September 1922."],
["180", "A trick used in extreme sports where a rider rotates half a turn while airborne and lands."],
["129", "The rank of Liberia in world population."],
["144", "A gross (a dozen dozen)."],
["35000", "The number of genes in a human being."],
["43", "The maximum number of cars participating in a NASCAR race in the Cup Series or Nationwide Series."],
["69", "The number Bill and Ted were thinking of when talking to their future selves."],
["587", "The outgoing port for email message submission."],
["1337", "The weight in pounds of the biggest pumpkin in the world."],
["114", "The number of chapters in the Quran."],
["10000000000000000000", "The total estimated insect population."],
["49", "The number of days and night Siddhartha Gautama spent meditating as a holy man."],
["25000000", "The number of different inhabited planets in the the Galactic Empire."],
["93", "The atomic number of neptunium."],
["151", "The number of episodes that TV series Malcolm in the Middle ran on the Fox Network from 2000 to 2006."],
["170", "Largest integer for which Google's built-in calculator function can compute the factorial."],
["52", "The approximate number of weeks in a year."],
["649", "The number of Pokémon as of Pokémon Black and White versions."],
["189", "The rank of Jersey in world population."],
["200", "The approximate number of volcanoes in Japan, which is home to 10% of the active volcanoes in the world."],
["186", "The number of odd numbered days during a non-leap year."],
["149", "The number of legal proceedings against 149 communists in Estonia in 1924."],
["19", "The final year a person is a teenager."],
["206", "Bones in the typical adult human body."],
["172000", "Tons of chocolate produced in Belgium in a year."],
["120", "The telephone number to report a car breakdown on the highway in Austria."],
["614", "The number of Commandments, according to Rabbi Fackenheimin, that should be in Judaism, vs. the traditional 613."],
["151", "Total number of types of Pokémon in the original set."],
["2", "The lowest channel of television in the United States, Canada, Argentina and Mexico on which television signals are broadcast."],
["451", "The temperature at which the paper in books ignites, giving the name to Ray Bradbury's novel Fahrenheit 451."],
]


pack = Repo.insert!(
  %Pack{
    name: "Wits and Wagers",
  }
)

Enum.each Enum.uniq(questions), fn question -> 
  q = Repo.insert!(%Question{
    instruction: "Best guess that is equal to or less than",
    content: Enum.at(question, 1),
    pack_id: pack.id,
  })

  %Answer{
    content: Enum.at(question, 0),
    question_id: q.id,
  } |> Repo.insert!
end
